[package]
name = "api-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "probectl"
path = "src/main.rs"

[dependencies]
shared.workspace = true
infra.workspace = true
client.workspace = true
tokio.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
serde_json.workspace = true
anyhow.workspace = true
